/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	time "time"

	robcontrollerv1alpha1 "github.com/robel-yemane/rob-controller/pkg/apis/robcontroller/v1alpha1"
	versioned "github.com/robel-yemane/rob-controller/pkg/client/clientset/versioned"
	internalinterfaces "github.com/robel-yemane/rob-controller/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/robel-yemane/rob-controller/pkg/client/listers/robcontroller/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// RobInformer provides access to a shared informer and lister for
// Robs.
type RobInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.RobLister
}

type robInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewRobInformer constructs a new informer for Rob type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewRobInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredRobInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredRobInformer constructs a new informer for Rob type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredRobInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.RobcontrollerV1alpha1().Robs(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.RobcontrollerV1alpha1().Robs(namespace).Watch(options)
			},
		},
		&robcontrollerv1alpha1.Rob{},
		resyncPeriod,
		indexers,
	)
}

func (f *robInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredRobInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *robInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&robcontrollerv1alpha1.Rob{}, f.defaultInformer)
}

func (f *robInformer) Lister() v1alpha1.RobLister {
	return v1alpha1.NewRobLister(f.Informer().GetIndexer())
}
