/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/robel-yemane/rob-controller/pkg/apis/robcontroller/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeRobs implements RobInterface
type FakeRobs struct {
	Fake *FakeRobcontrollerV1alpha1
	ns   string
}

var robsResource = schema.GroupVersionResource{Group: "robcontroller.robel.com", Version: "v1alpha1", Resource: "robs"}

var robsKind = schema.GroupVersionKind{Group: "robcontroller.robel.com", Version: "v1alpha1", Kind: "Rob"}

// Get takes name of the rob, and returns the corresponding rob object, and an error if there is any.
func (c *FakeRobs) Get(name string, options v1.GetOptions) (result *v1alpha1.Rob, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(robsResource, c.ns, name), &v1alpha1.Rob{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Rob), err
}

// List takes label and field selectors, and returns the list of Robs that match those selectors.
func (c *FakeRobs) List(opts v1.ListOptions) (result *v1alpha1.RobList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(robsResource, robsKind, c.ns, opts), &v1alpha1.RobList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.RobList{ListMeta: obj.(*v1alpha1.RobList).ListMeta}
	for _, item := range obj.(*v1alpha1.RobList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested robs.
func (c *FakeRobs) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(robsResource, c.ns, opts))

}

// Create takes the representation of a rob and creates it.  Returns the server's representation of the rob, and an error, if there is any.
func (c *FakeRobs) Create(rob *v1alpha1.Rob) (result *v1alpha1.Rob, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(robsResource, c.ns, rob), &v1alpha1.Rob{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Rob), err
}

// Update takes the representation of a rob and updates it. Returns the server's representation of the rob, and an error, if there is any.
func (c *FakeRobs) Update(rob *v1alpha1.Rob) (result *v1alpha1.Rob, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(robsResource, c.ns, rob), &v1alpha1.Rob{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Rob), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeRobs) UpdateStatus(rob *v1alpha1.Rob) (*v1alpha1.Rob, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(robsResource, "status", c.ns, rob), &v1alpha1.Rob{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Rob), err
}

// Delete takes name of the rob and deletes it. Returns an error if one occurs.
func (c *FakeRobs) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(robsResource, c.ns, name), &v1alpha1.Rob{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeRobs) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(robsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.RobList{})
	return err
}

// Patch applies the patch and returns the patched rob.
func (c *FakeRobs) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.Rob, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(robsResource, c.ns, name, pt, data, subresources...), &v1alpha1.Rob{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Rob), err
}
