/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"time"

	v1alpha1 "github.com/robel-yemane/rob-controller/pkg/apis/robcontroller/v1alpha1"
	scheme "github.com/robel-yemane/rob-controller/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// RobsGetter has a method to return a RobInterface.
// A group's client should implement this interface.
type RobsGetter interface {
	Robs(namespace string) RobInterface
}

// RobInterface has methods to work with Rob resources.
type RobInterface interface {
	Create(*v1alpha1.Rob) (*v1alpha1.Rob, error)
	Update(*v1alpha1.Rob) (*v1alpha1.Rob, error)
	UpdateStatus(*v1alpha1.Rob) (*v1alpha1.Rob, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.Rob, error)
	List(opts v1.ListOptions) (*v1alpha1.RobList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.Rob, err error)
	RobExpansion
}

// robs implements RobInterface
type robs struct {
	client rest.Interface
	ns     string
}

// newRobs returns a Robs
func newRobs(c *RobcontrollerV1alpha1Client, namespace string) *robs {
	return &robs{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the rob, and returns the corresponding rob object, and an error if there is any.
func (c *robs) Get(name string, options v1.GetOptions) (result *v1alpha1.Rob, err error) {
	result = &v1alpha1.Rob{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("robs").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Robs that match those selectors.
func (c *robs) List(opts v1.ListOptions) (result *v1alpha1.RobList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.RobList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("robs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested robs.
func (c *robs) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("robs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a rob and creates it.  Returns the server's representation of the rob, and an error, if there is any.
func (c *robs) Create(rob *v1alpha1.Rob) (result *v1alpha1.Rob, err error) {
	result = &v1alpha1.Rob{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("robs").
		Body(rob).
		Do().
		Into(result)
	return
}

// Update takes the representation of a rob and updates it. Returns the server's representation of the rob, and an error, if there is any.
func (c *robs) Update(rob *v1alpha1.Rob) (result *v1alpha1.Rob, err error) {
	result = &v1alpha1.Rob{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("robs").
		Name(rob.Name).
		Body(rob).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *robs) UpdateStatus(rob *v1alpha1.Rob) (result *v1alpha1.Rob, err error) {
	result = &v1alpha1.Rob{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("robs").
		Name(rob.Name).
		SubResource("status").
		Body(rob).
		Do().
		Into(result)
	return
}

// Delete takes name of the rob and deletes it. Returns an error if one occurs.
func (c *robs) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("robs").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *robs) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("robs").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched rob.
func (c *robs) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.Rob, err error) {
	result = &v1alpha1.Rob{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("robs").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
