apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: robs.robcontroller.robel.com
spec:
  group: robcontroller.robel.com
  version: v1alpha1
  names:
    kind: Rob
    plural: robs
  scope: Namespaced  

