apiVersion: robcontroller.robel.com/v1alpha1
kind: Rob
metadata:
  name: rob
spec:
  deploymentName: rob
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80

